desc "Build the jar file for given module."

lane :build do |options|
    module_name = options[:module]
    gradle(task: ":#{module_name}:assembleRelease")
end

lane :moveOutputToRoot do |options|
    module_name = options[:module]

    dest = "../build"
    sh("mkdir -p ../build")

    if Dir.exists? "../#{module_name}/build/outputs/aar"
        sh("mv ../#{module_name}/build/outputs/aar/* #{dest}")
    else
        sh("mv ../#{module_name}/build/libs/* #{dest}")
    end
end

lane :publish do |options|
    moduleName = options[:module]
    gradle(task: ":#{moduleName}:publish")
end

lane :publishAllToGithubRegistry do
    modules = ["compose-material"]

    modules.each do |module_name|
#         build(module: module_name)
        publish(module: module_name)
    end
end