# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-libraries:
    executor: docker
    docker:
      - image: cimg/base:current
    steps:
      - build
      - run:
          name: "Build all libraries"
          command: "fastlane buildAll"
    deploy-libraries:
      executor: docker
      docker:
        - image: cimg/base:current
      steps:
        - run:
            name: "Submit to Github Releases"
            command: "fastlane buildAll"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy-libraries:
    jobs:
      - build-libraries
      - deploy-libraries:
          requires:
          - build-libraries
      - filters:
          branches:
            only:
              master
