version: 2.1

jobs:
  spin-up-environment:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  deploy-libraries:
    jobs:
      - spin-up-environment
